---
Name: xd-instagram-feed
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - XD\InstagramFeed\Extensions\SiteConfigExtension
SilverStripe\Control\Director:
  rules:
    '__instaauth//$Action/$ID/$OtherID': 'XD\InstagramFeed\Controllers\InstagramAuthController'